name: Build and deploy .NET app to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: InvestNaijaAuthApi
  AZURE_RESOURCE_GROUP: InvestNaijaRG

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # or your version

      - name: Build
        run: dotnet build ./InvestNaijaAuth.csproj --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.INVESTNAAUTH_SPN }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: ./publish